// ---------------------------------------------------------------------------
// teams.js  —  Does every team that owns work actually have a queue to own it in
// ---------------------------------------------------------------------------
// WHY THIS IS ITS OWN BLOCK ON THE PAGE, SEPARATE FROM THE ITEM LIST
//
// A missing Zendesk group is a standing hole, not an event. It shows up in the
// item list only while something happens to be sitting in it — so on a quiet
// hour the page would report everything fine, and the next request routed to
// that team would land in nobody's queue exactly as the last one did. The
// condition is a property of the account, so it is reported as one, whether or
// not anything is waiting on it today.
//
// THE MECHANISM, WHICH IS THE DURABLE PART. A team is named by the routing
// table (a fact about Remote's org, the same in every account) and a group is
// minted by one Zendesk instance. Nothing keeps the two in step automatically:
// a team added to `escalationRouting.js` is unprovisioned from the moment it is
// added until somebody runs `scripts/setup-zendesk-groups.mjs` and
// `npm run sync-groups`, and in that window every ticket routed to it is tagged
// correctly and assignable nowhere. That window is the thing this file watches.
// It is not watching for one particular team.
//
// THE INSTANCE THAT PROMPTED IT, NOW HISTORY (and kept because the sequence is
// the argument for the check): on 2026-08-19 the routing table named eight
// owning teams and seven had a group. The missing one was Mobility Specialists,
// the team that approves every UC-04 work authorization — ticket #51 carried
// `queue_mobility_specialists` and sat in the account's default "Support"
// group, tagged correctly and queued nowhere, and nothing about the ticket
// looked wrong. Both that group and Local HR & Legal were created on
// 2026-08-20, and every routed team has had a group since. A dashboard that can
// only ever report faults teaches its reader to distrust it, so
// teamProvisioningSummary() below is able to SAY that — "all provisioned" is a
// result this view produced, not an absence of output.
//
// IT COMPARES AGAINST THE SYNCED MAP, NOT AGAINST A LIVE GROUP LIST. Listing
// groups needs the wider `read` OAuth scope; the synced map
// (src/shared/escalationGroupIds.js, regenerated by `npm run sync-groups`) is
// already the answer both the Node processes and the n8n graphs assign from. So
// a team missing here is missing in exactly the sense that matters: assignment
// will skip it. If the map is stale, that is itself the finding — nothing is
// assigning to that team either.
// ---------------------------------------------------------------------------

import { ESCALATION_ROUTES } from "../shared/escalationRouting.js";
import { groupIdFor } from "../shared/escalationGroupIds.js";

/**
 * Every team named by the routing table, with the use cases that route to it
 * and whether this account can actually assign to it.
 *
 * @returns {{name:string, groupId:number|null, provisioned:boolean,
 *   useCases:string[], roles:string[], detail:string}[]}
 */
export function teamProvisioning() {
  const teams = new Map();

  for (const [useCase, route] of Object.entries(ESCALATION_ROUTES)) {
    add(route.group, useCase, "ordinary review and approval");
    if (route.escalationGroup) add(route.escalationGroup, useCase, "escalations");
  }

  return [...teams.values()]
    .sort((a, b) => Number(a.provisioned) - Number(b.provisioned) || a.name.localeCompare(b.name))
    .map((team) => ({
      ...team,
      detail: team.provisioned
        ? `Group ${team.groupId}. Tickets for this team can be assigned to it.`
        : "This account has no Zendesk group by this name, so nothing routed here can be assigned. " +
          "Its tickets carry the right tag and land in whichever group Zendesk defaults an unassigned ticket to.",
    }));

  function add(name, useCase, role) {
    if (!name) return;
    if (!teams.has(name)) {
      const groupId = groupIdFor(name);
      teams.set(name, { name, groupId, provisioned: groupId !== null, useCases: [], roles: [] });
    }
    const team = teams.get(name);
    if (!team.useCases.includes(useCase)) team.useCases.push(useCase);
    if (!team.roles.includes(role)) team.roles.push(role);
  }
}

/**
 * The account-level verdict, so the page can state the good news as a finding
 * rather than leave the reader to infer it from a table with no red cells.
 *
 * FOUR STATES, AND THE FOURTH IS WHY THIS IS NOT A BOOLEAN:
 *
 *   "all_provisioned"   every team the routing table names has a group here.
 *                       Nothing is unassignable for want of a queue.
 *   "gaps"              some teams have a group and some do not. The named ones
 *                       are the fix, and it is one setup script away.
 *   "none_provisioned"  the map resolves NOTHING. That is not "N gaps" — it is
 *                       one gap with a different fix: `npm run sync-groups` has
 *                       never been run against this account, which
 *                       escalationGroupIds.js's own header calls a real and
 *                       expected state. Reporting it as nine separate missing
 *                       teams would send a reader to create nine groups that
 *                       may already exist.
 *   "no_teams_routed"   the routing table names nobody. Vacuously every team is
 *                       provisioned, and saying so would be the cheerful
 *                       reading of a broken routing table.
 *
 * @param {ReturnType<typeof teamProvisioning>} [teams]
 */
export function teamProvisioningSummary(teams = teamProvisioning()) {
  const total = teams.length;
  const missing = teams.filter((t) => !t.provisioned).map((t) => t.name);
  const provisioned = total - missing.length;

  const state =
    total === 0 ? "no_teams_routed" : missing.length === 0 ? "all_provisioned" : provisioned === 0 ? "none_provisioned" : "gaps";

  return { state, total, provisioned, missing, headline: HEADLINE[state]({ total, provisioned, missing }) };
}

const HEADLINE = Object.freeze({
  all_provisioned: ({ total }) =>
    `All ${total} teams the routing table hands work to have a Zendesk group in this account. ` +
    "Nothing routed anywhere is unassignable for want of a queue — which is a check that ran and passed, not a check with nothing to say.",
  gaps: ({ total, provisioned, missing }) =>
    `${provisioned} of ${total} teams have a Zendesk group. ${missing.length === 1 ? "This one does" : "These do"} not: ${missing.join(", ")}. ` +
    "Work routed there is tagged correctly and can be assigned nowhere, so it lands in the account default and nobody who owns it is looking. " +
    "Fix: scripts/setup-zendesk-groups.mjs, then `npm run sync-groups`.",
  none_provisioned: ({ total }) =>
    `None of the ${total} routed teams resolves to a group id, so no ticket anywhere is being assigned. ` +
    "That reads as one problem rather than as " +
    `${total} missing groups: the groups may well exist and the synced map be empty. Run \`npm run sync-groups\` before creating anything.`,
  no_teams_routed: () =>
    "The routing table names no owning team at all, so there is nothing to provision and nothing to check. " +
    "That is not the same as everything being fine.",
});
