// ---------------------------------------------------------------------------
// escalationGroupIds.js — Zendesk group NAME → group_id, resolved once
// ---------------------------------------------------------------------------
// WHY THIS FILE EXISTS SEPARATELY FROM escalationRouting.js
//
// `escalationRouting.js` answers WHICH TEAM owns an escalation. That is a fact
// about Remote's org and it is the same in every account. A numeric group id is
// a fact about ONE Zendesk instance — minted by Zendesk when the group is
// created — so putting ids in that module would make the source of truth wrong
// the moment anyone ran this against a different account. Two kinds of fact,
// two files.
//
// WHY THE IDS ARE BAKED IN RATHER THAN LOOKED UP AT RUNTIME
//
// Resolving a name to an id needs `GET /api/v2/groups`, which requires the
// `read` scope. The shared `ZendeskClient` deliberately defaults to the least
// privilege its ticket path needs (`tickets:read tickets:write`), so a runtime
// lookup 403s — "You are missing the following required scopes: groups:read,
// read" — and the escalation is tagged but NOT assigned. Observed live: portal
// ticket #38 carried `escalation_finance_ops` and sat in nobody's queue.
//
// The two ways out are to widen every running service's token, or to resolve
// the ids ONCE in a deliberate setup act and let the services read the answer.
// The second is what `workflows/nodes/assignRouting.js` already does for the
// n8n graphs, for exactly this reason; this file is the same answer for the
// Node processes, generated by the same script in the same pass so the two can
// never disagree.
//
// AN EMPTY MAP IS A REAL, EXPECTED STATE. It means the groups have not been
// created yet, and every caller must fall back to tagging the ticket and saying
// on it that assignment was skipped — a visible failure, never a silent one.
//
// Regenerate with `npm run sync-groups` (scripts/sync-zendesk-group-ids.mjs)
// AFTER scripts/setup-zendesk-groups.mjs has created the groups.
// ---------------------------------------------------------------------------

// --- GENERATED: Zendesk group name -> group_id, resolved from the live account
export const ESCALATION_GROUP_IDS = Object.freeze({
  "Finance Ops": 6168404929055,
  "HR Ops": 6168404929823,
  "Local HR & Legal": 9990000000002,
  "Mobility & Legal (Tier-2)": 6168394286495,
  "Mobility Legal (Tier-3)": 6168424846751,
  "Mobility Specialists": 9990000000003,
  "Payroll Ops": 6168442797343,
  "Tax Operations": 6168394287519,
  "Travel & Mobility Support": 6168404930335,
});
// --- END GENERATED ---

/**
 * The id for a group name, or null when this account has no such group.
 *
 * Null is the honest answer and callers must treat it as one: tag the ticket
 * and say assignment was skipped. Guessing an id would assign real work to the
 * wrong queue, which is worse than leaving it unassigned and saying so.
 *
 * @param {string|null|undefined} name
 * @returns {number|null}
 */
export function groupIdFor(name) {
  if (typeof name !== "string" || !name) return null;
  const id = ESCALATION_GROUP_IDS[name];
  return typeof id === "number" && Number.isInteger(id) && id > 0 ? id : null;
}
