// ---------------------------------------------------------------------------
// groupAssignment.js — turning "which team owns this" into a Zendesk group_id
// ---------------------------------------------------------------------------
// WHY THIS EXISTS, AND WHY IT IS NOT IN escalationRouting.js
//
// `escalationRouting.js` answers WHICH TEAM owns a hand-off. It is pure data
// and says so in its own header: no I/O, no account, no client. Resolving that
// team's NAME to a numeric `group_id` is I/O against one Zendesk instance, so
// it cannot live there without breaking the property that makes that module
// safe to import from anywhere (a policy engine, an n8n parity harness, a
// test).
//
// It is not in a use case either, because it is not a use-case fact. Three
// execution paths already need the same answer and had three different amounts
// of it:
//
//   - src/portal/server.js  — the reference implementation. Live read first,
//                             synced ids as the fallback, a sentence on the
//                             ticket when neither answered.
//   - workflows/nodes/assignRouting.js — the n8n port. No live read is possible
//                             in a Code node, so it carries the synced ids
//                             inline and emits the same sentence.
//   - src/uc01/workflow.js  — had NONE of it. A UC-01 escalation raised through
//                             the Node path (npm run live, npm run livedemo,
//                             the demo scripts — the path the demos drive)
//                             reached Zendesk with no owning-team tag and no
//                             group at all, while the same decision through n8n
//                             was tagged and assigned. Two paths, one of which
//                             silently dropped the hand-off. Nothing went red:
//                             the decision was correct, the letter was correct,
//                             and the ticket landed in an undifferentiated
//                             queue. docs/ESCALATION-DESTINATIONS.md §2.5.
//
// This module is that behaviour, once, so a fourth caller inherits it rather
// than reimplementing three quarters of it. The portal's own copy is
// deliberately untouched for now (another agent owns `src/portal/**` this
// session); the wording below is copied from it verbatim, and
// test/uc01Routing.test.js holds the two against each other so they cannot
// explain the same failure two different ways to the same specialist reading
// the same queue.
//
// WHAT IT DELIBERATELY DOES NOT DO
//
//   - It never creates a group. `scripts/setup-zendesk-groups.mjs` is the only
//     thing that does, deliberately and idempotently. A workflow that quietly
//     created org structure in a live account the first time something
//     escalated would be an outward act happening as a side effect.
//   - It never decides anything. It is given a decision's hand-off and answers
//     where it goes; it cannot change what the decision was.
//   - It never throws. A groups read that fails must not fail the escalation —
//     the ticket still gets its tags and a sentence saying assignment was
//     skipped and why. Visible failure, never silent.
// ---------------------------------------------------------------------------

import { groupIdFor } from "./escalationGroupIds.js";

/**
 * @typedef {object} GroupAssignment
 * @property {string|null} intendedGroup  the team this hand-off is addressed to
 * @property {boolean|null} escalated     did the automation give up, or is this
 *   the human gate working? null when no route is defined at all
 * @property {string[]} routingTags       the `queue_*` (+ `escalation_*`) tags
 * @property {boolean} assigned           did we resolve a real group_id?
 * @property {number|null} groupId
 * @property {"live"|"synced"|null} assignedFrom  where the id came from
 * @property {string|null} skippedReason  why it is unassigned, in words a
 *   REQUESTER may read verbatim — never a path, a source-file name or this
 *   project's own use-case index
 * @property {string|null} operatorRemedy  what a STAFF reader — a specialist
 *   working the ticket, not necessarily an engineer — should tell someone
 *   about it; null when there is nothing to do. Never a repo path, a CLI
 *   command or an API call, because that reader cannot run any of them
 *   (rca-ynsb). Only an operator-facing surface renders this.
 */

/**
 * Resolve a hand-off to a Zendesk group, reporting rather than throwing.
 *
 * THE LIVE READ IS AUTHORITATIVE; THE SYNCED IDS ARE THE FALLBACK, and the
 * order matters in both directions — this is `src/portal/server.js`'s reasoning
 * and it is copied rather than re-derived:
 *
 * A synced id is a CACHE (`src/shared/escalationGroupIds.js`, regenerated by
 * `npm run sync-groups`) and can be stale, so it must never overrule an account
 * that answered. When the read succeeds and says the group is not there, that
 * IS the answer — falling back then would assign real work to a group id this
 * account may no longer have. The fallback applies only when nothing
 * authoritative came back: the read threw, or there is no read at all.
 *
 * @param {object} args
 * @param {{group:string, tags:string[], escalated:boolean}|null} [args.handoff]
 *   the result of `handoffFor({useCase, decision})` — whose `group` is ALREADY
 *   the escalation team when the decision escalated, and whose `tags` already
 *   carry the `escalation_*` marker only when it belongs there. Null when the
 *   use case has no route defined at all.
 * @param {{listGroups?: () => Promise<Array<{id:number,name:string}>>}|null} [args.zendesk]
 * @param {string} args.useCase  named only so an unrouted use case can be said
 *   out loud on the ticket
 * @returns {Promise<GroupAssignment>}
 */
export async function resolveGroupAssignment({ handoff = null, zendesk = null, useCase }) {
  if (!handoff) {
    return {
      intendedGroup: null,
      escalated: null,
      routingTags: [],
      assigned: false,
      groupId: null,
      assignedFrom: null,
      // REQUESTER-SAFE, deliberately without the path or the use-case code
      // that used to live here — this is the same field the portal's result
      // panel renders verbatim (rca-ee04). The repository detail an operator
      // needs to fix it is real and is kept, in `operatorRemedy` below, which
      // only an operator-facing surface renders — same split as the two
      // branches beneath this one.
      skippedReason: `No team is currently set up to handle this kind of request, so this ticket was not routed to one. It has still been raised and recorded.`,
      // rca-ynsb: this used to name the repo file to edit
      // (`src/shared/escalationRouting.js`) — a fine instruction for whoever
      // owns that table and unusable noise for the specialist who actually
      // reads the ticket this lands on, who has no repo and no terminal.
      // Same content, phrased as who to tell rather than what to run.
      operatorRemedy: `No routing destination is configured for ${useCase} yet. Flag it to the team that maintains this system's escalation routing so one can be added.`,
    };
  }

  let group = null;
  let assignedFrom = null;
  let lookupError = null;
  let lookupAnswered = false;

  if (zendesk && typeof zendesk.listGroups === "function") {
    try {
      const groups = await zendesk.listGroups();
      group = (groups ?? []).find((g) => g && g.name === handoff.group) ?? null;
      lookupAnswered = true;
      if (group) assignedFrom = "live";
    } catch (err) {
      // A groups read that fails must not fail the escalation.
      lookupError = err?.message ?? String(err);
    }
  }

  if (!lookupAnswered) {
    const syncedId = groupIdFor(handoff.group);
    if (syncedId) {
      group = { id: syncedId, name: handoff.group };
      assignedFrom = "synced";
      // The read failure is no longer why this is unassigned — it IS assigned —
      // so it stops being the skipped reason. Where the id came from is still
      // worth saying, which `assignedFrom` does.
      lookupError = null;
    }
  }

  return {
    intendedGroup: handoff.group,
    // Stated rather than left to be inferred from the tag list: "a human is
    // expected to look" and "the automation could not finish" are different
    // hand-offs, and one tag for both made them indistinguishable.
    escalated: handoff.escalated,
    routingTags: handoff.tags,
    assigned: Boolean(group),
    groupId: group ? group.id : null,
    assignedFrom,
    // TWO READERS, TWO FIELDS, AND THEY WERE ONE STRING.
    //
    // `skippedReason` is spread onto a Zendesk ticket and onto the portal's
    // result panel, where the reader is the person who filed the request. It
    // used to end "Run scripts/setup-zendesk-groups.mjs to create the groups,
    // then re-run this escalation." — a path in this repository, printed to an
    // employee who cannot run it and would not want to. The remedy is real and
    // must not be lost: the audit and queue viewers are read by whoever
    // operates this system, and for them it is the most useful sentence here.
    //
    // So it splits rather than going away. `skippedReason` states what happened
    // to the ticket; `operatorRemedy` states what to do about it and is null
    // when there is nothing to do. A surface renders whichever its own reader
    // can act on — the requester-facing ones render the first alone.
    //
    // rca-ynsb: the split alone was not enough. `operatorRemedy` still landed
    // on the Zendesk internal note, and that note's actual reader is the
    // specialist working the ticket — someone with no repo and no terminal,
    // not the engineer who could run `scripts/setup-zendesk-groups.mjs` or
    // check a Zendesk API scope. So the CONTENT changed too: every remedy
    // below is now "flag it to the team that maintains X", never a path, a
    // command or an API call this reader cannot make.
    // THE GROUP-NOT-FOUND BRANCH GOT THE SAME SPLIT AS THE NO-OWNING-TEAM ONE
    // ABOVE, one bead later than that one. `handoff.group` (the Zendesk team
    // name) and `handoff.tags` (this project's own `queue_*`/`escalation_*`
    // routing vocabulary) are both internal detail — the same class of thing
    // the no-owning-team branch stopped naming a repo path for — so neither
    // belongs in a sentence the portal's result panel renders verbatim to the
    // person who filed the request. They still need to reach an OPERATOR, so
    // they move to `operatorRemedy`, prefixed onto the existing remedy rather
    // than dropped.
    skippedReason: group
      ? null
      : lookupError
        ? `This ticket could not be assigned to a team automatically. It has still been raised and recorded.`
        : `This ticket could not be assigned to a specific team automatically. It has still been raised and recorded.`,
    operatorRemedy: group
      ? null
      : lookupError
        ? // rca-ynsb: this used to say "Confirm the Zendesk credential can
          // read groups (GET /api/v2/groups), then re-run this escalation" —
          // an API call this note's reader (the specialist working the
          // ticket) has no way to make. Same fact, routed to who can act on
          // it.
          `The Zendesk groups could not be read (${lookupError}), so this ticket was tagged but not assigned. Flag it to the team that maintains this account's Zendesk credentials.`
        : // rca-ynsb: this used to end "Run scripts/setup-zendesk-groups.mjs
          // ... then npm run sync-groups ..." — a repo path and two CLI
          // commands, posted verbatim into a Zendesk internal note whose
          // actual reader (the specialist working the ticket) has neither a
          // checkout nor a terminal. The fact — this account is missing a
          // group this ticket needed — is exactly what that reader should
          // know; what changed is the call to action: tell the team that can
          // fix it, not run a script nobody on that side of the ticket can
          // run.
          `The Zendesk group "${handoff.group}" does not exist in this account, so this ticket was tagged ${handoff.tags.join(", ")} but NOT assigned. Flag it to the team that maintains this account's Zendesk groups so the missing group can be created and this escalation re-queued.`,
  };
}

/**
 * The assignment, as one sentence a specialist can read on the ticket.
 *
 * SAME VOCABULARY AS THE OTHER TWO PATHS, on purpose:
 * `workflows/nodes/assignRouting.js` emits `ASSIGNMENT SKIPPED — …` /
 * `ROUTING SKIPPED — …` and the portal prints the same `skippedReason`. A
 * person working one queue sees tickets from all three paths, and the same
 * failure must not arrive wearing three different explanations.
 *
 * @param {GroupAssignment} assignment
 * @returns {string}
 */
export function describeAssignment(assignment) {
  // THE INTERNAL NOTE KEEPS THE REMEDY, and that is the point of the split
  // rather than an exception to it. `skippedReason` alone goes to the portal's
  // result panel, where the reader filed the request and cannot run a script.
  // This note is posted with `public: false` and is read by staff, so the
  // sentence naming what to do about it is exactly what its reader wants.
  const remedy = assignment.operatorRemedy ? ` ${assignment.operatorRemedy}` : "";
  if (!assignment.intendedGroup) return `ROUTING SKIPPED — ${assignment.skippedReason}${remedy}`;
  if (!assignment.assigned) return `ASSIGNMENT SKIPPED — ${assignment.skippedReason}${remedy}`;

  const provenance =
    assignment.assignedFrom === "synced"
      ? // rca-ynsb: dropped the `npm run sync-groups` command — same reader
        // as above, same reason. The candour that matters here (this id came
        // from a cache, not a live read, and caches go stale) survives; the
        // instruction to run a script this reader cannot run does not.
        " — from a locally cached list of group ids, because the account could not be read live just now. That cache can go stale; if this looks wrong, flag it to the team that maintains this account's Zendesk groups."
      : assignment.assignedFrom === "live"
        ? " — read live from the account."
        : "";

  return (
    `Assigned to ${assignment.intendedGroup} (Zendesk group ${assignment.groupId}), ` +
    `tagged ${assignment.routingTags.join(", ")}${provenance}`
  );
}
